#!/bin/bash
# To use, store as .git/hooks/pre-push inside your repository and make sure
# it has execute permissions.

# run security/vulnerabilities scanner prior to pushing to repo

scanner=govulncheck

# detect if scanner is installed
if ! command -v ${scanner} &> /dev/null; then
    echo "==== ${scanner} is not installed. Make sure it is installed and path is set correctly"
    echo
    echo "     To install it you could use something similar to \"GOBIN=<DIR_OF_YOUR_CHOICE> go install golang.org/x/vuln/cmd/govulncheck@latest\""
    echo "     and make sure that <DIR_OF_YOUR_CHOICE> is added to PATH"
    exit 1
fi

echo "==== running ${scanner} from $0"

${scanner} ./...
